[package]
authors = ["Tobias Bucher <tobiasbucher5991@gmail.com>"]
name = "dirs"
version = "0.1.0"

[[bin]]
doc = false
name = "foobar"

[dependencies]
ole32-sys = "0.2.0"
shell32-sys = "0.1.1"
uuid-sys = "0.1.2"
winapi = "0.2.5"
xdg = "2.0.0"
